# Generated by Django 4.1.3 on 2022-11-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_tara', models.CharField(max_length=200, unique=True)),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
