# Generated by Django 4.1.3 on 2022-11-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_oras', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities.city')),
            ],
            options={
                'verbose_name_plural': 'Temperatures',
                'unique_together': {('id_oras', 'timestamp')},
            },
        ),
    ]
