# Generated by Django 4.1.3 on 2022-11-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_oras', models.CharField(max_length=200)),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
                ('id_tara', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'unique_together': {('id_tara', 'nume_oras')},
            },
        ),
    ]
