version: '3.3'

services:
  mqtt_api:
    build: .
    command: bash -c 'while !</dev/tcp/influxdb/$INFLUXDB_PORT; do sleep 1; done; while !</dev/tcp/mqtt_broker/$MQTTBROKER_PORT; do sleep 1; done; python3 mqtt-api/server.py'
    container_name: mqtt_api
    depends_on:
      - mqtt_broker
      - influxdb
    env_file:
      - ./.env
    networks:
      - api_broker
      - api_influx
    restart: always
  
  mqtt_broker:
    image: eclipse-mosquitto:2.0-openssl
    container_name: mqtt_broker
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - api_broker

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: influxdb_data_db
    networks:
      - api_influx
      - grafana_influx
  
  mqtt_grafana:
    image: grafana/grafana:latest
    container_name: mqtt_grafana
    ports:
      - '80:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: asistent
      GF_SECURITY_ADMIN_PASSWORD: grafanaSPRC2021
    networks:
      - grafana_influx

volumes:
  influxdb_data: {}
  grafana_data: {}

networks:
  api_broker: {}
  api_influx: {}
  grafana_influx: {}
