version: '3.3'

services:
  mqtt_api:
    build: .
    command: python3 mqtt-api/server.py
    container_name: mqtt_api
    depends_on:
      - mqtt_broker
      - mqtt_db
  
  mqtt_broker:
    image: eclipse-mosquitto:2.0-openssl
    container_name: mqtt_broker
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt_db:
    image: influxdb:2.6.0-alpine
    container_name: mqtt_db
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  
  mqtt_grafana:
    image: grafana/grafana:8.2.6
    container_name: mqtt_grafana
    ports:
      - '80:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - mqtt_db

volumes:
  influxdb_data: {}
  grafana_data: {}
