version: '3.3'

services:
  mqtt_api:
    build: .
    image: mqtt_api
    command: bash -c 'while ! nc -z influxdb 8086; do sleep 1; done; while ! nc -z mqtt_broker 1883; do sleep 1; done; python3 mqtt-api/server.py'
    depends_on:
      - mqtt_broker
      - influxdb
    env_file:
      - ./.env
    networks:
      - api_broker
      - api_influx
    volumes:
      - ./logs:/mqtt-api/logs
  
  mqtt_broker:
    image: eclipse-mosquitto:2.0-openssl
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - api_broker

  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: influxdb_data_db
      INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
      INFLUXDB_COORDINATOR_MAX_SELECT_BUCKETS: 0
    networks:
      - api_influx
      - grafana_influx
  
  mqtt_grafana:
    image: grafana/grafana:latest
    ports:
      - '80:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: asistent
      GF_SECURITY_ADMIN_PASSWORD: grafanaSPRC2021
    networks:
      - grafana_influx

volumes:
  influxdb_data: {}
  grafana_data: {}

networks:
  api_broker: {}
  api_influx: {}
  grafana_influx: {}
